# Generated by Django 3.0.4 on 2020-06-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='project',
            name='page',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pagina Web'),
        ),
    ]
